### ISSUE TITLE
Error running dashboard on remote cluster (stdout not writable)

### ISSUE THREAD

**Issue by dfenn** [sherpa-ai/sherpa#10]
I'm running into issues trying to run the dashboard on a remote cluster. 

Running the statement 

`study = sherpa.Study(parameters=parameters,
                     algorithm=alg,
                     lower_is_better=True)`

results in the following:

`Process Process-2:
Traceback (most recent call last):
  File "/hpcdata/usafa9/config/python/intelpython3/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/hpcdata/usafa9/config/python/intelpython3/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/hpcdata/usafa9/config/python/intelpython3/lib/python3.6/site-packages/flask/app.py", line 938, in run
    cli.show_server_banner(self.env, self.debug, self.name, False)
  File "/hpcdata/usafa9/config/python/intelpython3/lib/python3.6/site-packages/flask/cli.py", line 629, in show_server_banner
    click.echo(message)
  File "/hpcdata/usafa9/config/python/intelpython3/lib/python3.6/site-packages/click/utils.py", line 262, in echo
    file.write(message)
io.UnsupportedOperation: not writable`

The issue stems from the Click module, around line 218 of utils.py, which is `file = _default_text_stdout()`. Replacing this with `file = sys.stdout` resolves the issue for me.

I guess this is more an issue with Click than with Sherpa, but since I think my use case (running Sherpa on a remote cluster and accessing the dashboard via ssh tunneling) is probably common, I wanted to make you aware of it.

**Comment by LarsHH** [comment]
Hi dfenn! Thanks for posting this and providing a solution. Running Sherpa on a remote cluster and accessing the dashboard via tunneling is actually what I do most of the time too (actually the port is open on the VPN so I can directly access it without tunneling). I don't get this issue though. Therefore, it's super helpful that you posted this. Making the code run bug-free in different setups is one of the big challenges. I will think about whether there is a way this can be worked around without having to change the Click module
